---
# Codacy configuration file
# Focus on security issues only, disable style/linting tools

exclude_paths:
  - 'drizzle/**'
  - '**/*.sql'
  - 'node_modules/**'
  - '.next/**'
  - 'dist/**'
  - bun.lock
  - yarn.lock
  - package-lock.json

# Disable non-security tools
engines:
  # Disable style/linting tools
  stylelint:
    enabled: false
  eslint:
    enabled: false
  csslint:
    enabled: false
  remark-lint:
    enabled: false

  # Keep security-focused tools enabled
  bandit:
    enabled: true
  brakeman:
    enabled: true
  bundler-audit:
    enabled: true
  gosec:
    enabled: true
  semgrep:
    enabled: true
  trivy:
    enabled: true
